/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */

export interface IndexChatMessagesResponseMessage {
  message?: string | null;
  owned?: boolean;
  createdAt?: string;
}
