/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */
import type { IndexChatMessagesResponseMessage } from './indexChatMessagesResponseMessage';

export interface IndexChatMessagesResponse {
  userId?: string | null;
  messages?: IndexChatMessagesResponseMessage[] | null;
}
