/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */

export interface ItemTagsIndexResponse {
  id?: number;
  name?: string | null;
  description?: string | null;
  token?: string | null;
}
