/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */
import type { ItemTagField } from './itemTagField';

export interface ItemTagFieldGroup {
  language: string;
  fields: ItemTagField[];
}
