/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */
import type { LoginResponseUser } from './loginResponseUser';

export interface LoginResponse {
  user?: LoginResponseUser;
}
