/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */

export interface RegisterRequest {
  email: string;
  userName: string;
  password: string;
  confirmPassword: string;
}
