/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */

export interface UserResponse {
  id?: string | null;
  email?: string | null;
  userName?: string | null;
}
