/**
 * Generated by orval v6.11.0 🍺
 * Do not edit manually.
 * QrTagger
 * OpenAPI spec version: v1
 */

export interface WeatherForecast {
  date?: string;
  temperatureC?: number;
  readonly temperatureF?: number;
  summary?: string | null;
}
